# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

install! 'cocoapods',
  :integrate_targets => false,
  :deterministic_uuids => false # remove "Generated duplicate UUIDs" warnings

target 'BiometricsPOC' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for BiometricsPOC
  pod 'PassiveFaceLivenessNoSentryStatic', '~> 3.3.0'

  target 'BiometricsPOCTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'BiometricsPOC-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for BiometricsPOC-tvOS

  target 'BiometricsPOC-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|

    # TODO - The following is needed to ensure the "archive" step works in XCode.
    # It removes React & Yoga from the Pods project, as it is already included in the main project.
    # https://github.com/facebook/react-native/issues/20492
    # Without this, you'd see errors when you archive like:
    # "Multiple commands produce ... libReact.a"
    # "Multiple commands produce ... libyoga.a"

    targets_to_ignore = %w(React yoga)

    if targets_to_ignore.include? target.name
      target.remove_from_project
    end

    # This is necessary due to ClearSale SDK
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5'
    end
  end
end

source 'https://github.com/combateafraude/iOS.git'
source 'https://cdn.cocoapods.org/'
